---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: product-deployment
  labels:
    app: myapp
spec:
  replicas: 6
  selector:
    matchLabels:
      app: myapp
  template:
    metadata:
      labels:
        app: myapp
    spec:
      containers:
        - name: javawebcontainer
          image: hacker123shiva/springbt-in-docker:latest
